config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/user' => "trips#index", :as => :user_root
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :trips do
    resources :tasks, only: %i[create]
  end

  resources :tasks, only: %i[destroy update]

  get "users/:id/profile", to: "pages#profile", as: :user_profile
  # patch "trips/:trip_id/tasks/:id", to: "tasks#complete", as: :task_complete
  # patch "trips/:trip_id/tasks/:id", to: "tasks#uncomplete", as: :task_uncomplete
  post "trips/:trip_id/set_caretaker/:user_id", to: "tasks#set_caretaker", as: "set_caretaker"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates_inclusion_of :entry_type, in: ["Lockbox", "Digital Lock", "Hidden Key", "Other"], message: "%{value} is not a valid entry type"
  validates :start_date, :end_date, :name, :location, presence: true
  has_one_attached :photo
  has_one_attached :entry_photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
  has_many :tasks, through: :trips
  has_many :my_tasks, foreign_key: 'user_id', class_name: 'Task'
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
    @user = User.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show update destroy]

  def create
    @trip = Trip.find(params[:trip_id])
    @task = Task.new(task_params)
    @task.trip = @trip
    if @trip.tasks.where(date: params[:task][:date]).first
      @task.user = @trip.tasks.where(date: params[:task][:date]).first.user
    else
      @task.user = current_user
    end
    @task.category = Category.find(params[:task][:category])
    if @task.save
      redirect_to trip_path(@trip)
    else
      render "trips/show", status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @trip = @task.trip

    @task.done = !@task.done

    if @task.save
      redirect_to trip_path(@trip)
    else
      render "trips/show", status: :unprocessable_entity
    end
  end

  def set_caretaker
    @trip = Trip.find(params[:trip_id])
    @tasks = @trip.tasks.where(date: params[:date])
    @tasks.each do |task|
      task.user = User.find(params[:user_id])
      task.save
    end
    redirect_to trip_path(@trip)
  end

  def destroy
    @trip = @task.trip
    @task.destroy
    redirect_to trip_path(@trip), status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :date)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show edit update destroy]

  def index
    case current_user.role
    when "homeowner"
      @trips = Trip.where(user_id: current_user.id)
    when "caretaker"
      task_array = []
      Task.where(user_id: current_user.id).each { |task| task_array << task.trip }
      @trips = task_array.uniq
    else
      @trips = []
      "no trips yet"
    end
  end

  def new
    @trip = Trip.new
  end

  def show
    @task = Task.new
    @dates = ((Date.new(@trip.start_date.year, @trip.start_date.month, @trip.start_date.day))..(Date.new(@trip.end_date.year, @trip.end_date.month, @trip.end_date.day))).to_a
    @categories = Category.all
    caretaker_array = []
    @trip.tasks.each do |task|
      caretaker_array << task.user
    end
    @caretakers = caretaker_array.uniq
    case current_user.role
    when "homeowner"
      @tasks = @trip.tasks
    when "caretaker"
      @tasks = @trip.tasks.where(user_id: current_user)
    end
  end

  def edit
  end

  def update
    @trip.update(trip_params)
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    if @trip.destroy
      redirect_to trips_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :start_date, :end_date, :location, :entry_description, :entry_type, :entry_key, :photo)
  end

  def set_trip
    @trip = Trip.new(trip_params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def cloudinary_avatar(user)
    if user.photo.attached?
      cl_image_path user.photo.key
    else
      asset_path("noPicAvatar.png")
    end
  end

  def navbar_avatar(user)
    if user.photo.attached?
      cl_image_tag user.photo.key, alt: "#{ current_user.first_name } avatar", class: "rounded-circle", height: "32"
    else
      image_tag "noPicAvatar.png", alt: "Sign in or create account", class: "rounded-circle", height: "32"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoamHome | Organize house-sitting tasks easily</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <main class="container my-4">
      <%= yield %>
      <%= render "shared/flashes" %>
      <%= render "shared/footer" %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 text-center bg-primary bg-gradient shadow", style="--bs-bg-opacity: .7; width: 100vw; left: calc(-1 * (100vw - 100%) / 2);">
  <div class="container row mx-auto justify-between">
    <div class="col-md-4">
      <%= image_tag 'AwayFromHomeTransparent.svg', class: "img-fluid" %>
    </div>
    <div class="col-md-7 py-lg my-auto mx-auto ms-1 text-light">
      <h1 class="display-4 fw-bold">Keep your home running smoothly while you are away.</h1>
      <p class="lead fw-normal">Tired of coming home from a trip to dead plants and stolen mail? Whether you are away on business, vacation, or living as a digital nomad, RoamHome is the home-sitting task manager that makes it easy to keep your home in order.</p>
      <a class="btn btn-info btn-lg mt-3" href="<%= current_user ? "/trips" : "/users/sign_in?demo=true" %>"><%= current_user ? "My Trips" : "Try the Demo" %></a>
    </div>
  </div>
</div>

<div class="row align-items-center mt-4">
  <div class="col-md-4 order-md-2">
    <%= image_tag "friend.svg", class: "card-img-top mx-auto p-4" %>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Assign your friends, family, or neighbors to stop by on the days that are convenient for them.</h5>
        <p class="card-text">They'll know exactly what tasks need to be done on their assigned day—James knows to water the begonias when he comes on Tuesday, and Sandy knows how to top up the aquarium on Thursday.</p>
      </div>
    </div>
  </div>
</div>
<div class="row align-items-center mt-4">
  <div class="col-md-4">
    <%= image_tag "check.svg", class: "card-img-top mx-auto p-4" %>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Track in real time as tasks are completed</h5>
        <p class="card-text">With a simple checklist, your home-sitters have clear instructions to easily complete their assigned tasks and mark them done.</p>
      </div>
    </div>
  </div>
</div>
<div class="row align-items-center mt-4">
  <div class="col-md-4 order-md-2">
    <%= image_tag "island.svg", class: "card-img-top mx-auto p-4" %>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Peace of mind that your home is in good hands</h5>
        <p class="card-text">Whether you are in the next town over, or on the other side of the world, RoamHome gives you the peace of mind to not worry whether you left your garage door open or A/C on. Empower your friends and family to help in a way that is convenient for them.</p>
      </div>
    </div>
  </div>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
  <div class="col">
    <div class="card h-100 text-bg-primary">
      <%= image_tag "phone.svg", class: "card-img-top mx-auto p-4", style: "height: 150px;" %>
      <div class="card-body">
        <h5 class="card-title">No more 2am phone calls from another time zone</h5>
        <p class="card-text">Clear and explicit task instructions for your home-sitters prevents the dreaded middle of the night calls.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100 text-bg-primary">
      <%= image_tag "messages.svg", class: "card-img-top mx-auto p-4", style: "height: 150px;" %>
      <div class="card-body">
        <h5 class="card-title">No more unwieldy group chats and forgotten tasks</h5>
        <p class="card-text">Don't make your friend scroll through weeks of messages to find the lockbox code again.</p>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100 text-bg-primary">
      <%= image_tag "scooter.svg", class: "card-img-top mx-auto p-4", style: "height: 150px;" %>
      <div class="card-body">
        <h5 class="card-title">No more distractions if plans or home-sitters change</h5>
        <p class="card-text">Easily move and edit tasks and home-sitters.</p>
      </div>
    </div>
  </div>
</div>
<div class="mt-5 p-3 p-md-5 text-center bg-primary bg-gradient shadow", style="--bs-bg-opacity: .7;">
  <div class="container row mx-auto justify-between">
    <div class="col-md-12 py-lg my-auto mx-auto ms-1 text-light">
      <h1 class="display-4 fw-bold">Ready to RoamHome?</h1>
      <a class="btn btn-info btn-lg mt-3" href="<%= current_user ? "/trips" : "/users/sign_in?demo=true" %>"><%= current_user ? "My Trips" : "Try the Demo" %></a>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="row">
  <div class="col-12">
    <div class="card shadow w-100 rounded">
      <div class="card-body p-0">
        <div class="card-header py-3 d-flex align-items-center">
          <div class="flex-grow-1">
            <h5><strong>My Profile</strong></h5>
          </div>
          <div>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editModal">
              <i class="fa-regular fa-pen-to-square"></i>
            </button>
          </div>
        </div>
        <div class="card-body p-3 m-0">
          <%= cl_image_tag @user.photo.key, width: 100, crop: :fill, class: "img-thumbnail rounded-circle mb-2" %>
        <h5>
          <strong>Email:</strong>
          <p><%= @user.email %></p>
          <strong>First Name:</strong>
          <p><%= @user.first_name %></p>
          <strong>Last Name:</strong>
          <p><%= @user.last_name %></p>
        </h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">RoamHome | © <%= Date.today.year %></p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="https://github.com/jdepumpo/RoamHome" class="nav-link px-2 text-muted">Github</a></li>
    </ul>
  </footer>

app/views/shared/_navbar.html.erb
<header class="p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-end">
        <a href="/" class="me-lg-auto d-flex flex-no-wrap align-items-center me-4 mb-2 mb-lg-0 text-primary text-decoration-none">
          <%= image_tag "AwayFromHomeLogo.svg", style: "height: 64px;" %>
          <span class="fw-bold ms-2" style="font-size: 2rem;">RoamHome</span>
        </a>

        <% if current_user %>
        <ul class="nav col-12 col-lg-auto ms-lg-auto me-2 mb-2 justify-content-center mb-md-0">
          <li><a href="/trips" class="nav-link px-2 link-secondary">My Trips</a></li>
        </ul>

          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <%= navbar_avatar(current_user) %>
            </a>
            <ul class="dropdown-menu text-small" style="">
              <li><a class="dropdown-item" href="/trips/new">New Trip</a></li>
              <li><%= link_to "My Profile", user_profile_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %></li>
            </ul>
          </div>
        <% else %>
          <div class="col-md-3 text-end">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary me-2" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
          </div>
        <% end %>

      </div>
    </div>
  </header>

app/views/trips/_task.html.erb
<% tasks.order(:date).each_with_index do |task, i| %>
  <div class="accordion-item mt-1" id="<%= "#{dom_id(task)}_container" %>">
    <%= turbo_frame_tag dom_id(task) do %>
    <div class="accordion-header d-flex align-items-center" id="panelsStayOpen-heading<%=task.id%>">
      <% if task.done? %>
        <%= link_to task_path(task), data: {turbo_method: :patch} do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="text-light checkmark-done" style="width: 20px;" viewBox="0 0 20 20" fill="green">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
        <% end %>
        <button class="accordion-button collapsed d-flex px-2" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse<%=task.id%>" aria-expanded="true" aria-controls="panelsStayOpen-collapse<%=task.id%>">
            <span class="flex-grow-1 mx-2 text-secondary text-decoration-line-through"><%= task.name %></span>
        </button>
      <% else %>
        <%= link_to task_path(task), data: {turbo_method: :patch} do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="text-light checkmark-undone" style="width: 20px;" viewBox="0 0 20 20" fill="lightgrey">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
          </svg>
        <% end %>
        <button class="accordion-button collapsed d-flex px-2" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse<%=task.id%>" aria-expanded="true" aria-controls="panelsStayOpen-collapse<%=task.id%>">
            <span class="flex-grow-1 mx-2"><%= task.name %></span>
        </button>
      <% end %>
    </div>
    <div id="panelsStayOpen-collapse<%=task.id%>" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading<%=task.id%>">
      <div class="accordion-body d-flex flex-column">
        <%= task.description %>
        <%= link_to task_path(task), class: "btn btn-body-color mt-2 align-self-end", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?" } do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<%= render "form" %>

app/views/trips/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">My Trips</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to new_trip_path, class: "btn btn-primary my-2" do %>
      <strong>+</strong>
    <% end %>
  </div>
</div>

<% if @trips.nil? %>
  <p>You have no trips available...</p>
<% else %>
  <% @trips.each do |trip| %>
    <%= link_to trip_path(trip.id), class: "text-decoration-none text-reset" do %>
      <div class="p-4 p-md-5 mb-5 rounded text-bg-dark position-relative" style="background: center / cover no-repeat url('<%= (trip.photo.key) ? (cl_image_path trip.photo.key) : ('https://res.cloudinary.com/dxfg68ykv/image/upload/v1670496275/anthony-tan-PULWFiQi2aU-unsplash_gku5ka.jpg') %>')">
          <span class="position-absolute top-0 end-0 badge rounded-start bg-secondary">
            Starting in <%= (trip.start_date - Date.today).to_i %> days
          </span>
        <div class="col-md-8 px-0">
          <h2 class="display-4 fst-italic text-shadow"><%= trip.name %></h2>
          <p class="lead my-3 text-shadow"><%= trip.description %></p>
          <h3 class="mb-0 lead">
            <span class="badge bg-secondary">
              <i class="fa-solid fa-calendar-days text-light"></i>
              <span class="px-2"><%= trip.start_date.strftime('%a %d %b %Y') %> — <%= trip.end_date.strftime('%a %d %b %Y') %></span>
            </span>
          </h3>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/trips/new.html.erb
<%= render "form" %>

app/views/trips/show.html.erb
<%# ------------------ Trip image and details------------------------ %>

<div data-controller="flatpickr" data-start-date="<%= @trip.start_date %>" data-end-date="<%= @trip.end_date %>">

<%= render "shared/modals/new_modal", modal: "task", model: [@trip, @task], categories: @categories, trip: @trip %>
<%= render "shared/modals/access_info", model: @trip %>

<div class="row g-4">
  <div class="col-7">

    <div class="card px-0">
      <div class="p-4 p-md-5 rounded-top text-bg-dark position-relative" style="background: center / cover no-repeat url('<%= (@trip.photo.key) ? (cl_image_path @trip.photo.key) : ('https://res.cloudinary.com/dxfg68ykv/image/upload/v1670496275/anthony-tan-PULWFiQi2aU-unsplash_gku5ka.jpg') %>');">
        <span class="position-absolute top-0 end-0 badge rounded-start">
          Starting in <%= (@trip.start_date - Date.today).to_i %> days
        </span>
        <div class="col-md-8 px-0">
          <h2 class="display-4 fst-italic text-shadow"><%= @trip.name %></h2>
          <p class="lead my-3 text-shadow"><%= @trip.description %></p>
        <span class="lead">
          <span class="badge" style="background-color: #333333; font-size: 15px;">
            <i class="fa-solid fa-calendar-days text-light"></i>
            <span class="px-2" style="font-size:12px;"><%= @trip.start_date.strftime('%a %d %b %Y') %> — <%= @trip.end_date.strftime('%a %d %b %Y') %></span>
          </span>
        </span>
        </div>
      </div>
      <div class="card-footer bg-white rounded-bottom d-flex" style="justify-content:space-between">
        <button type="button" class="btn btn-primary text-white" data-bs-toggle="modal" data-bs-target="#accessModal">
          <i class="fa-solid fa-house-lock"></i> Location & Access
        </button>
        <div>
          <%= link_to edit_trip_path(@trip), class: "btn btn-white" do %>
            <i class="fa-solid fa-pen"></i>
          <% end %>
          <%= link_to trip_path(@trip), class: "btn btn-white", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this task?" } do %>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render "shared/modals/edit_modal", modal: "trip", model: @trip %>

<%# CARDS %>
    <div class="col-md-5 align-self-center">
      <div class="d-flex justify-content-center align-content-center w-100">
        <input placeholder="Select Dates" name="dates" data-flatpickr-target="calendarInput" class="d-none" data-action="change->flatpickr#highlightTask">
      </div>
    </div>

<%# ---------------------------NEW CODE HERE ---------------------------------------------- %>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 my-3">
  <h2>
    Tasks
    <% if current_user.role == "homeowner" %>
      <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#newModal">
        <i class="fa-solid fa-plus"></i>
      </button>
    <% end  %>
  </h2>
</div>

<%# --------------------------- PAST CODE HERE ---------------------------------------------- %>

<div class="swiper mt-0" data-controller="swiper">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
  <% slide_index = 0 %>
  <% @dates.in_groups_of(4, false) do |dates| %>
    <div class="swiper-slide">
      <div class="card-deck mx-5 mb-5">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">

          <% dates.each_with_index do |date, i| %>
              <div class="col" id="<%= date %>" data-slide-index="<%= slide_index %>" data-start-date="<%= @trip.start_date %>" data-end-date="<%= @trip.end_date %>">
                <div class="card h-100">
                  <div class="card-body">
                    <% if @tasks.where(date: date).present? %>
                      <% if @tasks.where(date: date).first.user.photo.attached? %>
                        <%= cl_image_tag @tasks.where(date: date).first.user.photo.key, class: "rounded-circle float-end", style: "max-height: 2.5rem;" %>
                      <% else %>
                        <%= image_tag "noPicAvatar.png", class: "taskuseravatar" %>
                      <% end %>
                    <% end %>
                    <% if @dates.count <= 10 %>
                      <h6 class="card-title mb-2">Day <%= (date - @trip.start_date).to_i + 1  %></h5>
                      <h6 class="card-subtitle mb-2 text-muted"><%= date.strftime("%a, %B %d") %></h6>
                    <% else %>
                      <h5 class="card-title mb-2"><%= date.strftime("%a, %B %d") %></h5>
                      <h6 class="card-subtitle mb-2 text-muted">Day <%= (date - @trip.start_date).to_i + 1 %></h6>
                    <% end %>
                    <hr />

            <%# <span class="badge bg-secondary rounded-pill"><%= task.category.name </span> %>
                    <div class="accordion accordion-flush mt-2">
                      <% if  @tasks.where(date: date).count == 0 %>
                        <p class="mb-2 text-muted">No tasks today...</p>
                      <% else %>
                        <%= render "trips/task", tasks: @tasks.where(date: date), day: i+1 %>
                      <% end %>
                    </div>

                  </div>
                  <div class="card-footer mt-2 d-flex justify-content-end bg-light">
                    <% if @tasks.where(date: date).first %>
                      <div class="btn-group btn-group-sm" role="group">
                        <% if @tasks.where(date: date).first %>
                          <%=link_to @tasks.where(date: date).first.user.first_name, user_profile_path(@tasks.where(date: date).first.user), class: "btn btn-light btn-sm"%>
                        <% end %>
                        <button type="button" class="btn btn-light btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"></button>
                        <ul class="dropdown-menu" style="min-width: 300px;">
                          <% @caretakers.each do |caretaker| %>
                            <%= link_to set_caretaker_path(@trip, caretaker, date: date), data: { turbo_method: :post } do %>
                              <li><%= cl_image_tag caretaker.photo.key, style: "width:30px;", class: "rounded-circle mx-2 py-2" %><span><%= "#{caretaker.first_name} #{caretaker.last_name}" %></span></li>
                            <% end %>
                          <% end %>
                        </ul>
                      </div>
                    <% elsif %>
                      <span style="padding-top: 6px;">&nbsp;</span>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% slide_index += 1 %>
        </div>
      </div>
    </div>
  <% end %>
</div>


  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>

      <div class="d-flex align-items-center border-bottom px-4" style="margin-top: 0; ">
        <h1 class="h2" style="margin-bottom:15px; margin-right:10px">Caretakers</h1>

      </div>
      <div class="d-flex justify-content-center px-0">
        <% @caretakers.each do |caretaker| %>
          <div class="caretaker-item mx-4 d-flex flex-column">
            <div class="caretaker-pic d-flex justify-content-center">
              <%= link_to user_profile_path(caretaker) do %>
                <%= cl_image_tag caretaker.photo.key, style: "width: 50px; font-size:12px", class: "rounded-circle" %>
              <% end %>
            </div>
            <div class="caretaker-name mt-2">
              <%= link_to user_profile_path(caretaker) do %>
                <%= caretaker.first_name %>
                <%= caretaker.last_name %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>